"""its a migration, innit?

Revision ID: 41c761a0fdc1
Revises: 
Create Date: 2025-12-08 15:05:51.082706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c761a0fdc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signature_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature_type', sa.String(length=20), nullable=False, comment='Type: order, allowance, transfer'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.String(length=42), nullable=False),
    sa.Column('target_activity_id', sa.Integer(), nullable=True, comment='Target activity ID from copytrading DB'),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('is_order_signed', sa.Boolean(), nullable=False, comment='Order signature completed (replay protection)'),
    sa.Column('is_commission_signed', sa.Boolean(), nullable=False, comment='Commission transfer signed (replay protection)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('service_name', sa.String(length=50), nullable=True),
    sa.Column('rate_limited', sa.Boolean(), nullable=False),
    sa.Column('volume_limited', sa.Boolean(), nullable=False),
    sa.Column('validation_failed', sa.Boolean(), nullable=False),
    sa.Column('token_id', sa.String(length=100), nullable=True),
    sa.Column('token_address', sa.String(length=42), nullable=True),
    sa.Column('amount_usdc', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_target_activity', 'signature_audit_log', ['target_activity_id'], unique=False)
    op.create_index('idx_type_created', 'signature_audit_log', ['signature_type', 'created_at'], unique=False)
    op.create_index('idx_user_created', 'signature_audit_log', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_wallet_created', 'signature_audit_log', ['wallet_address', 'created_at'], unique=False)
    op.create_index(op.f('ix_signature_audit_log_id'), 'signature_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_signature_audit_log_signature_type'), 'signature_audit_log', ['signature_type'], unique=False)
    op.create_index(op.f('ix_signature_audit_log_target_activity_id'), 'signature_audit_log', ['target_activity_id'], unique=False)
    op.create_index(op.f('ix_signature_audit_log_user_id'), 'signature_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_signature_audit_log_wallet_address'), 'signature_audit_log', ['wallet_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signature_audit_log_wallet_address'), table_name='signature_audit_log')
    op.drop_index(op.f('ix_signature_audit_log_user_id'), table_name='signature_audit_log')
    op.drop_index(op.f('ix_signature_audit_log_target_activity_id'), table_name='signature_audit_log')
    op.drop_index(op.f('ix_signature_audit_log_signature_type'), table_name='signature_audit_log')
    op.drop_index(op.f('ix_signature_audit_log_id'), table_name='signature_audit_log')
    op.drop_index('idx_wallet_created', table_name='signature_audit_log')
    op.drop_index('idx_user_created', table_name='signature_audit_log')
    op.drop_index('idx_type_created', table_name='signature_audit_log')
    op.drop_index('idx_target_activity', table_name='signature_audit_log')
    op.drop_table('signature_audit_log')
    # ### end Alembic commands ###
